export const RouteConst = {
    main:'/',
    mypage:'/mypage',
    mystamp:'/mystamps',
    myblog:'/myblogs',
    mybookmark:'/mybookmarks',
    mymission:'/mymissions',
    login:'/login',
    signup:'/signup',
    welcome:'/welcome',
    findemail: '/find/email',
    findemailmethod1: '/find/email/method1',
    findemailmethod2: '/find/email/method2',
    findpw: '/find/pw',
    findpwmethod1: '/find/pw/method1',
    findpwmethod2: '/find/pw/method2',
    oauth:'/oauth-token',
}