export const locations = [
	{ name: "시작", ENG: "Start", direction: "S" },
	{ name: "서울", ENG: "Seoul", direction: "H" },
	{ name: "부산", ENG: "Busan", direction: "H" },
	{ name: "인천", ENG: "Incheon", direction: "H" },
	{ name: "대구", ENG: "Daegu", direction: "H" },
	{ name: "제주", ENG: "Jeju", direction: "S" },
	{ name: "대전", ENG: "Daejeon", direction: "V" },
	{ name: "광주", ENG: "Gwangju", direction: "V" },
	{ name: "울산", ENG: "Ulsan", direction: "V" },
	{ name: "세종", ENG: "Sejong", direction: "V" },
	{ name: "자유여행", ENG: "Anywhrere", direction: "S" },
	{ name: "충남", ENG: "Chungnam", direction: "H" },
	{ name: "경남", ENG: "Gyeongnam", direction: "H" },
	{ name: "전남", ENG: "Jeonnam", direction: "H" },
	{ name: "충북", ENG: "Chungbuk", direction: "H" },
	{ name: "울릉도/독도", ENG: "Dokdo", direction: "S" },
	{ name: "경북", ENG: "Gyungbuk", direction: "V" },
	{ name: "전북", ENG: "Jeonbuk", direction: "V" },
	{ name: "강원", ENG: "Gangwon", direction: "V" },
	{ name: "경기", ENG: "Gyeonggi", direction: "V" },
	{ name: "시작", ENG: "Start", direction: "S" },
];

export const moveOrder = [
	[5, 5],
	[5, 4],
	[5, 3],
	[5, 2],
	[5, 1],
	[5, 0],
	[4, 0],
	[3, 0],
	[2, 0],
	[1, 0],
	[0, 0],
	[0, 1],
	[0, 2],
	[0, 3],
	[0, 4],
	[0, 5],
	[1, 5],
	[2, 5],
	[3, 5],
	[4, 5],
];
