export const locations = [
	{ name: "시작", ENG: "STR", direction: "S" },
	{ name: "서울", ENG: "SEO", direction: "H", cityId: "1" },
	{ name: "부산", ENG: "BSN", direction: "H", cityId: "2" },
	{ name: "인천", ENG: "INC", direction: "H", cityId: "3" },
	{ name: "대구", ENG: "DGU", direction: "H", cityId: "4" },
	{ name: "제주", ENG: "JEJ", direction: "S", cityId: "5" },
	{ name: "대전", ENG: "DJN", direction: "V", cityId: "6" },
	{ name: "광주", ENG: "GWJ", direction: "V", cityId: "7" },
	{ name: "울산", ENG: "ULS", direction: "V", cityId: "8" },
	{ name: "세종", ENG: "SJN", direction: "V", cityId: "9" },
	{ name: "자유 여행", ENG: "ANY", direction: "S", cityId: "10" },
	{ name: "충남", ENG: "CHN", direction: "H", cityId: "11" },
	{ name: "경남", ENG: "GYN", direction: "H", cityId: "12" },
	{ name: "전남", ENG: "JNM", direction: "H", cityId: "13" },
	{ name: "충북", ENG: "CHB", direction: "H", cityId: "14" },
	{ name: "울릉도", ENG: "ULD", direction: "S", cityId: "15" },
	{ name: "경북", ENG: "GYB", direction: "V", cityId: "16" },
	{ name: "전북", ENG: "JNB", direction: "V", cityId: "17" },
	{ name: "강원", ENG: "GWN", direction: "V", cityId: "18" },
	{ name: "경기", ENG: "GNG", direction: "V", cityId: "19" },
	{ name: "시작", ENG: "STR", direction: "S" },
];

export const moveOrder = [
	[5, 5],
	[5, 4],
	[5, 3],
	[5, 2],
	[5, 1],
	[5, 0],
	[4, 0],
	[3, 0],
	[2, 0],
	[1, 0],
	[0, 0],
	[0, 1],
	[0, 2],
	[0, 3],
	[0, 4],
	[0, 5],
	[1, 5],
	[2, 5],
	[3, 5],
	[4, 5],
];
